-- Default table for general information
CREATE TABLE Items (
    Id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Description TEXT,
    Recyclable BOOLEAN NOT NULL DEFAULT FALSE,
    Sellable BOOLEAN NOT NULL DEFAULT FALSE,
    SellPrice INT UNSIGNED NOT NULL DEFAULT 0,
    Repairable BOOLEAN NOT NULL DEFAULT FALSE,
    RepairCost INT UNSIGNED NOT NULL DEFAULT 0,
    StackSize INT UNSIGNED NOT NULL DEFAULT 1,
    RarityId BIGINT UNSIGNED NOT NULL,
    TypeId BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (RarityId) REFERENCES ItemRarities(Id),
    FOREIGN KEY (TypeId) REFERENCES ItemTypes(Id)
);

-- Recycle relation
CREATE TABLE Recyclables (
    ConsumeId BIGINT UNSIGNED NOT NULL,
    ReceiveId BIGINT UNSIGNED NOT NULL,
    Count INT UNSIGNED NOT NULL DEFAULT 1,
    PRIMARY KEY (ConsumeId, ReceiveId),
    FOREIGN KEY (ConsumeId) REFERENCES Items(Id),
    FOREIGN KEY (ReceiveId) REFERENCES Items(Id)
);

-- Item rarity enum table
CREATE TABLE ItemRarities (
    Id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Colour VARCHAR(6) NOT NULL DEFAULT '000000' -- Colour code
);

CREATE TABLE ItemTypes (
    Id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL
);
