CREATE TABLE Maps (
    Id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Description TEXT
);

CREATE TABLE MapEvents (
    Id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Description TEXT
);

CREATE TABLE MapLootsTypes (
    Id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE MapLoots (
    MapId BIGINT UNSIGNED NOT NULL,
    MapLootTypeId BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (MapId, MapLootTypeId),
    FOREIGN KEY (MapId) REFERENCES Maps(Id),
    FOREIGN KEY (MapLootTypeId) REFERENCES MapLootTypes(Id)
);
